apiVersion: skaffold/v4beta2
kind: Config
manifests: 
      rawYaml: 
        - ./infra/k8s/*
build:
  # local:
    # push: false
  googleCloudBuild:
    projectId: ticketing-dev-380723
  artifacts:
    - image: us.gcr.io/ticketing-dev-380723/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' 
            dest: .